// Copyright(c) 2023-present, Atlas.
// Distributed under the MIT License (http://opensource.org/licenses/MIT)

#pragma once

#include "utility/delegate.hpp"

#define DECLARE_DELEGATE(alias)                                                                                                                                                                         using alias = atlas::Delegate<void>
#define DECLARE_DELEGATE_ONE_PARAM(alias, type1, name1)                                                                                                                                                 using alias = atlas::Delegate<void, type1>
#define DECLARE_DELEGATE_TWO_PARAMS(alias, type1, name1, type2, name2)                                                                                                                                  using alias = atlas::Delegate<void, type1, type2>
#define DECLARE_DELEGATE_THREE_PARAMS(alias, type1, name1, type2, name2, type3, name3)                                                                                                                  using alias = atlas::Delegate<void, type1, type2, type3>
#define DECLARE_DELEGATE_FOUR_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4)                                                                                                     using alias = atlas::Delegate<void, type1, type2, type3, type4>
#define DECLARE_DELEGATE_FIVE_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5)                                                                                       using alias = atlas::Delegate<void, type1, type2, type3, type4, type5>
#define DECLARE_DELEGATE_SIX_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6)                                                                          using alias = atlas::Delegate<void, type1, type2, type3, type4, type5, type6>
#define DECLARE_DELEGATE_SEVEN_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7)                                                          using alias = atlas::Delegate<void, type1, type2, type3, type4, type5, type6, type7>
#define DECLARE_DELEGATE_EIGHT_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8)                                            using alias = atlas::Delegate<void, type1, type2, type3, type4, type5, type6, type7, type8>
#define DECLARE_DELEGATE_NINE_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8, type9, name9)                               using alias = atlas::Delegate<void, type1, type2, type3, type4, type5, type6, type7, type8, type9>
#define DECLARE_DELEGATE_TEN_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8, type9, name9, type10, name10)                using alias = atlas::Delegate<void, type1, type2, type3, type4, type5, type6, type7, type8, type9, type10>

#define DECLARE_DELEGATE_RET(alias, ret)                                                                                                                                                                using alias = atlas::Delegate<ret>
#define DECLARE_DELEGATE_ONE_PARAM_RET(alias, ret, type1, name1)                                                                                                                                        using alias = atlas::Delegate<ret, type1>
#define DECLARE_DELEGATE_TWO_PARAMS_RET(alias, ret, type1, name1, type2, name2)                                                                                                                         using alias = atlas::Delegate<ret, type1, type2>
#define DECLARE_DELEGATE_THREE_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3)                                                                                                         using alias = atlas::Delegate<ret, type1, type2, type3>
#define DECLARE_DELEGATE_FOUR_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4)                                                                                            using alias = atlas::Delegate<ret, type1, type2, type3, type4>
#define DECLARE_DELEGATE_FIVE_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5)                                                                              using alias = atlas::Delegate<ret, type1, type2, type3, type4, type5>
#define DECLARE_DELEGATE_SIX_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6)                                                                 using alias = atlas::Delegate<ret, type1, type2, type3, type4, type5, type6>
#define DECLARE_DELEGATE_SEVEN_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7)                                                 using alias = atlas::Delegate<ret, type1, type2, type3, type4, type5, type6, type7>
#define DECLARE_DELEGATE_EIGHT_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8)                                   using alias = atlas::Delegate<ret, type1, type2, type3, type4, type5, type6, type7, type8>
#define DECLARE_DELEGATE_NINE_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8, type9, name9)                      using alias = atlas::Delegate<ret, type1, type2, type3, type4, type5, type6, type7, type8, type9>
#define DECLARE_DELEGATE_TEN_PARAMS_RET(alias, ret, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8, type9, name9, type10, name10)       using alias = atlas::Delegate<ret, type1, type2, type3, type4, type5, type6, type7, type8, type9, type10>

#define DECLARE_MULTICAST_DELEGATE(alias)                                                                                                                                                               using alias = atlas::MulticastDelegate<>
#define DECLARE_MULTICAST_DELEGATE_ONE_PARAM(alias, type1, name1)                                                                                                                                       using alias = atlas::MulticastDelegate<type1>
#define DECLARE_MULTICAST_DELEGATE_TWO_PARAMS(alias, type1, name1, type2, name2)                                                                                                                        using alias = atlas::MulticastDelegate<type1, type2>
#define DECLARE_MULTICAST_DELEGATE_THREE_PARAMS(alias, type1, name1, type2, name2, type3, name3)                                                                                                        using alias = atlas::MulticastDelegate<type1, type2, type3>
#define DECLARE_MULTICAST_DELEGATE_FOUR_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4)                                                                                           using alias = atlas::MulticastDelegate<type1, type2, type3, type4>
#define DECLARE_MULTICAST_DELEGATE_FIVE_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5)                                                                             using alias = atlas::MulticastDelegate<type1, type2, type3, type4, type5>
#define DECLARE_MULTICAST_DELEGATE_SIX_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6)                                                                using alias = atlas::MulticastDelegate<type1, type2, type3, type4, type5, type6>
#define DECLARE_MULTICAST_DELEGATE_SEVEN_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7)                                                using alias = atlas::MulticastDelegate<type1, type2, type3, type4, type5, type6, type7>
#define DECLARE_MULTICAST_DELEGATE_EIGHT_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8)                                  using alias = atlas::MulticastDelegate<type1, type2, type3, type4, type5, type6, type7, type8>
#define DECLARE_MULTICAST_DELEGATE_NINE_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8, type9, name9)                     using alias = atlas::MulticastDelegate<type1, type2, type3, type4, type5, type6, type7, type8, type9>
#define DECLARE_MULTICAST_DELEGATE_TEN_PARAMS(alias, type1, name1, type2, name2, type3, name3, type4, name4, type5, name5, type6, name6, type7, name7, type8, name8, type9, name9, type10, name10)      using alias = atlas::MulticastDelegate<type1, type2, type3, type4, type5, type6, type7, type8, type9, type10>